### ISSUE TITLE
Error when trying to authorize Real Debrid

### ISSUE THREAD

**Issue by kolekan** [Gujal00/ResolveURL#143]
I'm getting this error when trying to authorize my RD account. Kodi 19.4 Win 10 64bit.
```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
               Error Type: <class 'http.client.IncompleteRead'>
               Error Contents: IncompleteRead(0 bytes read)
               Traceback (most recent call last):
                 File "G:\Kodi.19\system\python\Lib\http\client.py", line 555, in _get_chunk_left
                   chunk_left = self._read_next_chunk_size()
                 File "G:\Kodi.19\system\python\Lib\http\client.py", line 522, in _read_next_chunk_size
                   return int(line, 16)
               ValueError: invalid literal for int() with base 16: b''
               
               During handling of the above exception, another exception occurred:
               
               Traceback (most recent call last):
                 File "G:\Kodi.19\system\python\Lib\http\client.py", line 572, in _readall_chunked
                   chunk_left = self._get_chunk_left()
                 File "G:\Kodi.19\system\python\Lib\http\client.py", line 557, in _get_chunk_left
                   raise IncompleteRead(b'')
               http.client.IncompleteRead: IncompleteRead(0 bytes read)
               
               During handling of the above exception, another exception occurred:
               
               Traceback (most recent call last):
                 File "G:\Kodi.19\portable_data\addons\script.module.resolveurl\lib\default.py", line 195, in <module>
                   sys.exit(main())
                 File "G:\Kodi.19\portable_data\addons\script.module.resolveurl\lib\default.py", line 191, in main
                   url_dispatcher.dispatch(mode, queries)
                 File "G:\Kodi.19\portable_data\addons\script.module.resolveurl\lib\resolveurl\lib\url_dispatcher.py", line 85, in dispatch
                   self.func_registry[mode](*args, **kwargs)
                 File "G:\Kodi.19\portable_data\addons\script.module.resolveurl\lib\default.py", line 67, in auth_rd
                   if realdebrid.RealDebridResolver().authorize_resolver():
                 File "G:\Kodi.19\portable_data\addons\script.module.resolveurl\lib\resolveurl\plugins\realdebrid.py", line 295, in authorize_resolver
                   js_result = json.loads(self.net.http_GET(url, headers=self.headers).content)
                 File "G:\Kodi.19\portable_data\addons\script.module.resolveurl\lib\resolveurl\lib\net.py", line 389, in content
                   html = self._response.read()
                 File "G:\Kodi.19\system\python\Lib\http\client.py", line 465, in read
                   return self._readall_chunked()
                 File "G:\Kodi.19\system\python\Lib\http\client.py", line 579, in _readall_chunked
                   raise IncompleteRead(b''.join(value))
               http.client.IncompleteRead: IncompleteRead(0 bytes read)
               -->End of Python script error report<--
```

**Comment by Gujal00** [comment]
Please do not post log snippets as it is not useful. Always use kodi logfile uploader to upload the full `DEBUG` log and provide the link here

Anyway looks like RD have banned ResolveURL's User Agent which looks like `ResolveURL for Kodi/5.1.xx`
Using a browser User Agent works fine. Can you test with commit https://github.com/Gujal00/ResolveURL/commit/77c2744f751d396e1adb9cf1c25624947f0821b8 and report back?

**Comment by kolekan** [comment]
Same error with latest commit. I revert back to 5.1.70 and works without error. But i think that it is a random situation when it works or not.

**Comment by Gujal00** [comment]
Same as #142

**Comment by Gujal00** [comment]
ResolveURL 5.1.71 released with changes as suggested by RD tech.
Please test and get back if working or not

**Comment by kolekan** [comment]
I test it and it authorize with no problem. Thanks
