### ISSUE TITLE
streamsb not work

### ISSUE THREAD

**Issue by soter80** [Gujal00/ResolveURL#199]
Hui Guys, treamsb not work, erro HTTP 404 but vidoe is online and work on browser.

this is the log
```
2022-09-12 15:04:55.654 T:14964   ERROR <general>: ResolveURL: HTTPError Error - From: StreamSB Link: https://sblanh.com/o59acl3wlwis.html: HTTP Error 404: Not Found
2022-09-12 15:04:55.656 T:14964   DEBUG <general>: ResolveURL: Traceback (most recent call last):
                                                     File "C:\Users\PCPRENO1\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 194, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
                                                     File "C:\Users\PCPRENO1\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\streamsb.py", line 67, in get_media_url
                                                       html = self.net.http_GET(eurl, headers=headers).content
                                                     File "C:\Users\PCPRENO1\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\net.py", line 236, in http_GET
                                                       return self._fetch(url, headers=headers, compression=compression)
                                                     File "C:\Users\PCPRENO1\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\net.py", line 347, in _fetch
                                                       response = urllib_request.urlopen(req, timeout=15)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by Gujal00** [comment]
Fixed in https://github.com/Gujal00/ResolveURL/commit/1cde1f4cc4a54f8efc78bbf08f0ad0ab0db6b8d1

**Comment by soter80** [comment]
thanks bro

**Comment by mortegai** [comment]
Patch not working when "File owner disabled downloads".

get_embedurl doesn't work now.
