### ISSUE TITLE
Linksnappy error when trying to authenticate my credentials - works on older version of resolveurl which is urlresolver

### ISSUE THREAD

**Issue by ohmichael** [Gujal00/ResolveURL#304]
I thought about purchasing linksnappy & I have the free version but it's not allowing me to authenticate my credentials for linksnappy but allows me to on urlresolver plugin weird but I thought you deserved to know.
The only way I can get it to work is by going into notepad of some kind and manually typing it in and saving it the reopening kodi.
But unless I do it that way I'll get an error message upon hitting re-authenticate or whatever the thing says to login.
How come exodus is the only addon that seems to pull linksnappy links - I know I have up to 10gb free with my trial but I should be seeing linksnappy on all my addons that use resolveurl - the addons like exodus seem to work well but they use urlresolver extension - anyways thought there was a bug in resolveurl for linksnappy in the python file so I thought it needed to be looked at.
Is there anyway you could implement more debrid services to resolveurl also besides the one's everyone uses because the main 3 debrid services I can't really count on.
I just ran across linksnappy & thought I'd like to have it fixed so I can use it in my better addons because exodus is behind in the works - hasn't been updated in months but these newer one's seem to only work with coco or forks of coco which you can't help but the one's that work with resolveurl it would help a lot because you worked on resolveurl.
Sorry I wrote alot if hope you aren't mad but I'm tired of real debrid always being down - I tried premiumize I don't like it - and alldebrid I just started but it seems to mimic real debrid's hosters - I wanted something with more hoster choices and linksnappy seems to work well. But it's giving me an error when logging in. I didn't know how else to say it so I just threw all my ideas on here.
Thanks, Michael - I'm probably wasting my time asking the above because it seems people are moving away from resolveurl & more to alternative scraper extensions but you probably already know that. But if it's possible to look at linksnappy python file in resolveurl that be great & all I would be hopeful for you to consider. Either that or the settings file is corrupt & giving out errors. I'm receiving an error from somewhere all I know.

**Comment by Gujal00** [comment]
@Twilight0 Can you check if linksnappy is working in ResolveURL, Thanks

**Comment by Gujal00** [comment]
> Is there anyway you could implement more debrid services to resolveurl also besides the one's everyone uses because the main 3 debrid services I can't really count on

Real-Debrid, AllDebrid, Premiumize, Debrid-Link and Linksnappy are the only ones that work with ResolveURL currently. if there is an issue with Linksnappy plugin, @Twilight0 who maintains the plugin can fix it.
If there are other debrid providers keen to work with ResolveURL, then of course support can be added. It is up to the providers to work with ResolveURL devs to get it added.
 
Need a full debug log to see what is happening anyway
1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi **(Important)**
4. Go into to ResolveURL settings and try authorizing linksnappy (wait for the error message)
5. Come out of ResolveURL settings
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

> I'm probably wasting my time asking the above because it seems people are moving away from resolveurl & more to alternative scraper extensions but you probably already know that

Some addons are moving away from scraping hosters and only support torrents and easynews. Those addons wont need ResolveURL. There are a lot of other addons that still use hosters and all of those still use ResolveURL and thats the reason ResolveURL is still maintained.

**Comment by alonistore** [comment]
`2023-01-29 13:47:58.705 T:1295831   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'resolveurl.plugins.linksnappy' has no attribute 'LinksnappyResolver'
                                                   Traceback (most recent call last):
                                                     File "/Users/xxx/Library/Application Support/Kodi/addons/script.module.resolveurl/lib/default.py", line 195, in <module>
                                                       sys.exit(main())
                                                     File "/Users/xxx/Library/Application Support/Kodi/addons/script.module.resolveurl/lib/default.py", line 191, in main
                                                       url_dispatcher.dispatch(mode, queries)
                                                     File "/Users/xxx/Library/Application Support/Kodi/addons/script.module.resolveurl/lib/resolveurl/lib/url_dispatcher.py", line 85, in dispatch
                                                       self.func_registry[mode](*args, **kwargs)
                                                     File "/Users/xxx/Library/Application Support/Kodi/addons/script.module.resolveurl/lib/default.py", line 132, in auth_ls
                                                       if linksnappy.LinksnappyResolver().authorize_resolver():
                                                   AttributeError: module 'resolveurl.plugins.linksnappy' has no attribute 'LinksnappyResolver'
                                                   -->End of Python script error report<--
                                                   
`

**Comment by Twilight0** [comment]
Give me a few days, I 'll try to fix it because I don't have a premium account.

**Comment by alonbtm** [comment]
you don't need premium account,  just try to press Authorisation My Account :)

**Comment by Twilight0** [comment]
> you don't need premium account, just try to press Authorisation My Account :)

I need elite/premium account to enhance the whole plugin and fix it, too. Have a look here: https://github.com/Gujal00/ResolveURL/issues/2

**Comment by alonbtm** [comment]
i resolve the issue,

need to change  linksnappy.**LinksnappyResolver()**.authorize_resolver(): To   linksnappy.LinkSnappyResolver().authorize_resolver(): 
 line 133 on default.py

and  ls = linksnappy.**LinksnappyResolver**() to ls = linksnappy.LinkSnappyResolver()
 line  142 on default.py. 

```
@url_dispatcher.register(MODES.AUTH_LS)
def auth_ls():
    kodi.close_all()
    kodi.sleep(500)  # sleep or authorize won't work for some reason
    from resolveurl.plugins import linksnappy
    
    if linksnappy.LinkSnappyResolver().authorize_resolver():
        kodi.notify(msg=kodi.i18n('ls_authorized'), duration=5000)


@url_dispatcher.register(MODES.RESET_LS)
def reset_ls():
    kodi.close_all()
    kodi.sleep(500)  # sleep or reset won't work for some reason
    from resolveurl.plugins import linksnappy
    ls = linksnappy.LinkSnappyResolver()
    ls.reset_authorization()
    kodi.notify(msg=kodi.i18n('ls_auth_reset'), duration=5000)


```

**Comment by Gujal00** [comment]
> File "/Users/xxx/Library/Application Support/Kodi/addons/script.module.resolveurl/lib/default.py", line 132, in auth_ls if linksnappy.LinksnappyResolver().authorize_resolver(): AttributeError: module 'resolveurl.plugins.linksnappy' has no attribute 'LinksnappyResolver' -->End of Python script error report<--
> 

Thanks for that log, the fix is pushed in https://github.com/Gujal00/ResolveURL/commit/b62431cfa27a86dd8761ca3753261cb2a4ed88cf

But as @Twilight0 mentioned he still has to work on the plugin to get the resolve_all feature code added. But you should be able to use it without that for now as not many addons use the resolve_all feature

**Comment by ohmichael** [comment]
I managed to get some addons to work with urlresolver because there’s no error showing on there just resolveurl lol. Doesn’t matter as I’ll probably not buy into linksnappy as they aren’t answering my questions & their support stinks hard to reach anyone at linksnappy but it’s good to know there’s errors in resolveurl for just linksnappy I saw. Could be others not sure I was just doing linksnappy & ran into it. You can manually fix it by adding the login credentials & codes into it via a notepad & reopening kodi but who wants to do all that lol.
