### ISSUE TITLE
Dropload

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#474]
Hello from Germany.

I have a problem.
is the resolver the problem or is it me.

here is the log

2023-06-06 18:06:36.916 T:28376   error <general>: ResolveURL: AttributeError Error - From: DropLoad Link: https://dropload.io/embed-1b18nu91yfl5.html: 'NoneType' object has no attribute 'groups'
2023-06-06 18:06:36.920 T:28376    info <general>: Traceback (most recent call last):
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\default.py", line 27, in <module>
                                                       run()
                                                     File "<string>", line 21, in run
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\xstream.py", line 109, in parseUrl
                                                       cHosterGui().stream(playMode, sSiteName, sFunction, url)
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\resources\lib\gui\hoster.py", line 318, in stream
                                                       self.play(siteResult)
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\resources\lib\gui\hoster.py", line 69, in play
                                                       data = self._getInfoAndResolve(siteResult)
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\resources\lib\gui\hoster.py", line 44, in _getInfoAndResolve
                                                       link = mediaUrl if siteResult['resolved'] else resolver.resolve(mediaUrl)
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 128, in resolve
                                                       return source.resolve()
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 195, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\plugins\dropload.py", line 29, in get_media_url
                                                       return helpers.get_media_url(
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\lib\helpers.py", line 232, in get_media_url
                                                       source_list = scrape_sources(html, result_blacklist, scheme, patterns, generic_patterns)
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\lib\helpers.py", line 184, in scrape_sources
                                                       html += get_packed_data(html)
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\lib\helpers.py", line 88, in get_packed_data
                                                       packed_data += jsunpack.unpack(match.group(1))
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\lib\jsunpack.py", line 53, in unpack
                                                       payload, symtab, radix, count = _filterargs(source)
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\lib\jsunpack.py", line 94, in _filterargs
                                                       args = re.search(argsregex, source, re.DOTALL).groups()
                                                   AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by Gujal00** [comment]
error due to a change in helpers.py in last release, fixed now
