### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#475]
Hello from germany.

Here is the same problem as yesterday with Dropload.
```
2023-06-07 18:22:49.956 T:32704    info <general>: [xStream] -> [cinemathek]: -> [hoster]: resolve: https://upstream.to/embed-h4grtjzuth54.html
2023-06-07 18:22:50.193 T:32704   error <general>: ResolveURL: AttributeError Error - From: UpStream Link: https://upstream.to/embed-h4grtjzuth54.html: 'NoneType' object has no attribute 'groups'
2023-06-07 18:22:50.252 T:32704    info <general>: Traceback (most recent call last):
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\default.py", line 27, in <module>
                                                       run()
                                                     File "<string>", line 21, in run
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\xstream.py", line 109, in parseUrl
                                                       cHosterGui().stream(playMode, sSiteName, sFunction, url)
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\resources\lib\gui\hoster.py", line 318, in stream
                                                       self.play(siteResult)
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\resources\lib\gui\hoster.py", line 69, in play
                                                       data = self._getInfoAndResolve(siteResult)
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\resources\lib\gui\hoster.py", line 44, in _getInfoAndResolve
                                                       link = mediaUrl if siteResult['resolved'] else resolver.resolve(mediaUrl)
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 128, in resolve
                                                       return source.resolve()
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 195, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\plugins\upstream.py", line 49, in get_media_url
                                                       html += helpers.get_packed_data(html)
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\lib\helpers.py", line 88, in get_packed_data
                                                       packed_data += jsunpack.unpack(match.group(1))
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\lib\jsunpack.py", line 53, in unpack
                                                       payload, symtab, radix, count = _filterargs(source)
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\lib\jsunpack.py", line 94, in _filterargs
                                                       args = re.search(argsregex, source, re.DOTALL).groups()
                                                   AttributeError: 'NoneType' object has no attribute 'groups'
                                                   
2023-06-07 18:23:03.066 T:10584   error <general>: Playlist Player: skipping unplayable item: 0, path 
```

**Comment by Gujal00** [comment]
Okay I have updated `helpers.py` in https://github.com/Gujal00/ResolveURL/commit/81ecb191187f5c8345cbf37ea7e2ff11fc8e379c
If you find any other broken resolver, then I think I will rollback helpers.py to how it used to be and rework on the resolver (kwik) that needed the change in helpers file

**Comment by DWH-WFC** [comment]
Ok upstream works great again. Dropload still works after the change.

If I find another resolver with the error, I'll create an issue and link it to the other two so you can keep track.

Thank you for your quick help.
greetings from Germany
