### ISSUE TITLE
WAAW plugin has stopped working (CaptchaWindow issue)

### ISSUE THREAD

**Issue by repobal** [Gujal00/ResolveURL#878]
Hello.
We are developers of the Balandro addon. 
For a few days now, the WAAW plugin has stopped working (before the box to solve the captcha appeared).
Now it gives this error:
`
 'CaptchaWindow' object has no attribute 'temp_file'
`

Here is the log file:

```python
2024-09-02 04:29:33.514 T:10804   error <general>: ResolveURL: AttributeError Error - From: Waaw Link: https://waaw.to/embed_player.php?vid=T0xWVG83TStncTJvRENTSTZ3Z1M0UT09: 'CaptchaWindow' object has no attribute 'temp_file'
2024-09-02 04:29:33.591 T:10804   error <general>: ######## ERROR #########
2024-09-02 04:29:33.591 T:10804   error <general>:     [Balandro.servers.waaw.get_video_url] Traceback (most recent call last):
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\plugin.video.balandro\servers\waaw.py", line 66, in get_video_url
                                                       resuelto = resolveurl.resolve(page_url)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 133, in resolve
                                                       return source.resolve()
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 205, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\waaw.py", line 75, in get_media_url
                                                       window = captcha_window.CaptchaWindow(image, 400, 400)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\captcha_window.py", line 35, in init
                                                       self.temp_file = self.create_temp_image()
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\captcha_window.py", line 68, in create_temp_image
                                                       self.remove_temp_image()
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\captcha_window.py", line 157, in remove_temp_image
                                                       if os.path.exists(self.temp_file):
                                                   AttributeError: 'CaptchaWindow' object has no attribute 'temp_file'
```

**Comment by Gujal00** [comment]
Can you please test with PR #874

**Comment by repobal** [comment]
> Can you please test with PR #874

Of course. We have tested it and with the **captcha_window.py** script updated in the Lib folder, the WAAW plugin is working correctly again, so we expect a new resolveurl release as soon as possible so that our users have this issue resolved. THX.

Regards.
