### ISSUE TITLE
error in realdebrid.py __check_cache function

### ISSUE THREAD

**Issue by pikdum** [Gujal00/ResolveURL#879]
I've been running into this error for a bit now:

```
2024-09-01 18:51:40.964 T:2433    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'resolveurl.resolver.ResolverError'>
                                                   Error Contents: Unexpected Exception during RD Unrestrict: 'list' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.resolveurl/lib/resolveurl/plugins/realdebrid.py", line 66, in get_media_url
                                                       cached = self.__check_cache(media_id)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.resolveurl/lib/resolveurl/plugins/realdebrid.py", line 219, in __check_cache
                                                       _hash_info = js_result.get(_hash, {})
                                                                    ^^^^^^^^^^^^^
                                                   AttributeError: 'list' object has no attribute 'get'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.haru/haru.py", line 513, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.haru/haru.py", line 504, in router
                                                       route["function"](**filtered_args)
                                                     File "/storage/.kodi/addons/plugin.video.haru/haru.py", line 332, in play_nyaa
                                                       return _play_nyaa(selected_file=selected_file, magnet=magnet)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.haru/haru.py", line 309, in _play_nyaa
                                                       all_urls = resolveurl.resolve(magnet, return_all=True)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.resolveurl/lib/resolveurl/__init__.py", line 133, in resolve
                                                       return source.resolve()
                                                              ^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.resolveurl/lib/resolveurl/hmf.py", line 200, in resolve
                                                       url_list = resolver.get_media_url(self._host, self._media_id, return_all=self._return_all)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/script.module.resolveurl/lib/resolveurl/plugins/realdebrid.py", line 196, in get_media_url
                                                       raise ResolverError('Unexpected Exception during RD Unrestrict: %s' % e)
                                                   resolveurl.resolver.ResolverError: Unexpected Exception during RD Unrestrict: 'list' object has no attribute 'get'
                                                   -->End of Python script error report<--
```

Seems to be happening with `resolveurl.resolve(magnet, return_all=True)` if the torrent isn't cached.
Currently testing a fix, will make a PR if it works.

I'm thinking the issue is js_result being a list instead of a dict, not sure why though.

**Comment by Gujal00** [comment]
Thanks buddy, can you check if it is resolved by https://github.com/Gujal00/ResolveURL/commit/afa2a22cfc8934ed9409b25e030c3aae6ed01ee6
I did it slightly differently

**Comment by pikdum** [comment]
Tested your fix, looks good.
