### ISSUE TITLE
Moflix Resolver

### ISSUE THREAD

**Issue by DWH-WFC** [Gujal00/ResolveURL#929]
Hello from Germany

the moflix resolver dont works.

Video Link: `https://moflix-stream.fans/v/QcVFLVdbBJza/` , `https://moflix-stream.fans/v/eRKnkItPLZ9L/`

Log File:
```
2024-11-16 15:07:18.723 T:644492    info <general>: SMR Link Tester: Version: |1.1.13| Queries: |{'mode': 'main'}|
2024-11-16 15:07:18.723 T:644492    info <general>: SMR Link Tester: Running on: Python 3.8.15 (default, Oct 17 2022, 02:39:57) [MSC v.1929 64 bit (AMD64)]|OpenSSL 1.1.1q  5 Jul 2022
2024-11-16 15:07:18.723 T:644492    info <general>: SMR Link Tester: Args: |['plugin://plugin.video.smr_link_tester/', '21', '', 'resume:false']|
2024-11-16 15:07:20.140 T:645100    info <general>: SMR Link Tester: Version: |1.1.13| Queries: |{'mode': 'play_link', 'link': 'https://moflix-stream.fans/v/QcVFLVdbBJza/'}|
2024-11-16 15:07:20.140 T:645100    info <general>: SMR Link Tester: Running on: Python 3.8.15 (default, Oct 17 2022, 02:39:57) [MSC v.1929 64 bit (AMD64)]|OpenSSL 1.1.1q  5 Jul 2022
2024-11-16 15:07:20.140 T:645100    info <general>: SMR Link Tester: Args: |['plugin://plugin.video.smr_link_tester/', '22', '?mode=play_link&link=https%3A%2F%2Fmoflix-stream.fans%2Fv%2FQcVFLVdbBJza%2F', 'resume:false']|
2024-11-16 15:07:20.140 T:645100    info <general>: SMR Link Tester: Playing Link: |https://moflix-stream.fans/v/QcVFLVdbBJza/|
2024-11-16 15:07:20.181 T:645100    info <general>: SMR Link Tester: Link Supported: |https://moflix-stream.fans/v/QcVFLVdbBJza/| Resolvers: MoflixStream
2024-11-16 15:07:20.946 T:645100   error <general>: ResolveURL: JSONDecodeError Error - From: MoflixStream Link: https://moflix-stream.fans/v/QcVFLVdbBJza/: Expecting value: line 1 column 1 (char 0)
2024-11-16 15:07:20.994 T:615784   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.smr_link_tester/?mode=play_link&link=https%3A%2F%2Fmoflix-stream.fans%2Fv%2FQcVFLVdbBJza%2F]
```

Error:
```
2024-11-16 15:09:39.915 T:644832   error <general>: ResolveURL: JSONDecodeError Error - From: MoflixStream Link: https://moflix-stream.fans/v/eRKnkItPLZ9L/: Expecting value: line 1 column 1 (char 0)
2024-11-16 15:09:39.917 T:644832    info <general>: Traceback (most recent call last):
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\default.py", line 27, in <module>
                                                       run()
                                                     File "<string>", line 96, in run
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\xstream.py", line 117, in parseUrl
                                                       cHosterGui().stream(playMode, sSiteName, sFunction, url)
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\resources\lib\gui\hoster.py", line 325, in stream
                                                       self.play(siteResult)
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\resources\lib\gui\hoster.py", line 69, in play
                                                       data = self._getInfoAndResolve(siteResult)
                                                     File "C:\Program Files\Kodi\portable_data\addons\plugin.video.xstream\resources\lib\gui\hoster.py", line 44, in _getInfoAndResolve
                                                       link = mediaUrl if siteResult['resolved'] else resolver.resolve(mediaUrl)
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 133, in resolve
                                                       return source.resolve()
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 205, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
                                                     File "C:\Program Files\Kodi\portable_data\addons\script.module.resolveurl\lib\resolveurl\plugins\moflix.py", line 39, in get_media_url
                                                       data = json.loads(r.group(1))
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by DWH-WFC** [comment]
Hello New Resolver from Moflix.

Video Link:
https://moflix.upns.xyz/#9actp

Is it possible to integrate this into the resolver?
Or does this require a separate one?

**Comment by DWH-WFC** [comment]
How can I pass this to the resolver? Ia:// Link?

**Comment by Gujal00** [comment]
The resolver does not play, all it does is return a playable url. In your addon you should have logic to play HLS urls using Inputstream Adaptive

**Comment by DWH-WFC** [comment]
thanks

**Comment by Gujal00** [comment]
Lets keep this issue open as `https://moflix-stream.fans/` is still broken

**Comment by valdess821-collab** [comment]
Ich Brauche hilfe bei Supernatural Ich kann Supernatural nicht Sehen bei molfix-stream

**Comment by valdess821-collab** [comment]
Könnt ihr mir hilfen bitte

**Comment by solbu** [comment]
> Ich Brauche hilfe bei Supernatural Ich kann Supernatural nicht Sehen bei molfix-stream

You need to use English.
