### ISSUE TITLE
cannot authorize real debrid accounts error!

### ISSUE THREAD

**Issue by DeDuplicate** [Gujal00/ResolveURL#942]
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'urllib.error.HTTPError'>
                                                   Error Contents: HTTP Error 403: Forbidden
                                                   Traceback (most recent call last):
                                                     File "C:\Users\DeDuplicate\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\default.py", line 195, in <module>
                                                       sys.exit(main())
                                                     File "C:\Users\DeDuplicate\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\default.py", line 191, in main
                                                       url_dispatcher.dispatch(mode, queries)
                                                     File "C:\Users\DeDuplicate\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\url_dispatcher.py", line 85, in dispatch
                                                       self.func_registry[mode](*args, **kwargs)
                                                     File "C:\Users\DeDuplicate\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\default.py", line 67, in auth_rd
                                                       if realdebrid.RealDebridResolver().authorize_resolver():
                                                     File "C:\Users\DeDuplicate\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\realdebrid.py", line 279, in authorize_resolver
                                                       js_result = json.loads(self.net.http_GET(url, headers=self.headers).content)
                                                     File "C:\Users\DeDuplicate\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\net.py", line 245, in http_GET
                                                       return self._fetch(url, headers=headers, compression=compression, redirect=redirect, timeout=timeout)
                                                     File "C:\Users\DeDuplicate\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\net.py", line 360, in _fetch
                                                       response = urllib_request.urlopen(req, timeout=timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 403: Forbidden
                                                   -->End of Python script error report<--

**Comment by bleak-lodge** [comment]
Playback also fails with 403: Forbidden.
They seem to have blacklisted smr's user agent. Altering the ua playback works.

**Comment by Spank1433** [comment]
I cannot authorize my RD account on Kodi through ResolveURL

**Comment by Gujal00** [comment]
> Playback also fails with 403: Forbidden. They seem to have blacklisted smr's user agent. Altering the ua playback works.

That is weird, not blacklisting the Client-ID but blacklisting the UA doesnt seem right. May be it is some other issue like last time with ALPN headers.
Will check in a day or two

**Comment by bleak-lodge** [comment]
It is weird, but altering the UA to a random one makes playback work again, so I don't know what to think.

**Comment by Gujal00** [comment]
Okay having `Kodi` in the UA is the issue. Looks like they have banned that keyword. pushing a fix now
