### ISSUE TITLE
CLICKNUPLOAD plugin --> HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by repobal** [Gujal00/ResolveURL#965]
Hello.
We are developers of the Balandro addon and all logs are from Spain.

CLICKNUPLOAD exists and plays correctly; in All valid LINKS it ALWAYS gives this Result:

```python
2024-12-18 07:02:18.879 T:6288    error <general>: ResolveURL: HTTPError Error - From: ClickNUpload Link: https://clicknupload.org/8tmrx5kw12hr: HTTP Error 400: Bad Request
2024-12-18 07:02:19.033 T:6288    error <general>: ######## ERROR #########
2024-12-18 07:02:19.033 T:6288    error <general>:     [Balandro.servers.clicknupload.get_video_url] Traceback (most recent call last):
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\plugin.video.balandro\servers\clicknupload.py", line 100, in get_video_url
                                                       resuelto = resolveurl.resolve(page_url)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 133, in resolve
                                                       return source.resolve()
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 205, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\clicknupload.py", line 50, in get_media_url
                                                       data.update(captcha_lib.do_captcha(html))
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\captcha_lib.py", line 68, in do_captcha
                                                       return do_recaptcha_v2(recaptcha_v2.group(1))
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\captcha_lib.py", line 128, in do_recaptcha_v2
                                                       token = recaptcha_v2.UnCaptchaReCaptcha().processCaptcha(sitekey, lang='en')
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\recaptcha_v2.py", line 141, in processCaptcha
                                                       html = self.net.http_GET('http://www.google.com/recaptcha/api/fallback?k=%s' % (key), headers=headers).content
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\net.py", line 245, in http_GET
                                                       return self._fetch(url, headers=headers, compression=compression, redirect=redirect, timeout=timeout)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\net.py", line 360, in _fetch
                                                       response = urllib_request.urlopen(req, timeout=timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 569, in error
return self._call_chain(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by Gujal00** [comment]
They have moved from google invisible recaptcha to cloudflare hcaptcha. Can not be bypassed for now. Plugin is broken
