### ISSUE TITLE
MEGAUP plugin --> File cannot be located or removed

### ISSUE THREAD

**Issue by repobal** [Gujal00/ResolveURL#967]
Hello again.
We are developers of the Balandro addon and all logs are from Spain.

MEGAUP on All valid LINKS ALWAYS gives this Result:

```python
2024-12-18 06:24:52.174 T:12492   error <general>: ResolveURL: ResolverError Error - From: MegaUpNet Link: https://megaup.net/4f7a90dc7577d83f19f6a4591ac6a336/Um9ib3Qgc2FsdmFqZSAoMjAyNCk=.LAT.mp4: File cannot be located or removed
2024-12-18 06:24:52.245 T:12492   error <general>: ######## ERROR #########
2024-12-18 06:24:52.245 T:12492   error <general>:     [Balandro.servers.megaup.get_video_url] Traceback (most recent call last):
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\plugin.video.balandro\servers\megaup.py", line 128, in get_video_url
                                                       resuelto = resolveurl.resolve(page_url)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 133, in resolve
                                                       return source.resolve()
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 205, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\megaupnet.py", line 42, in get_media_url
                                                       raise ResolverError('File cannot be located or removed')
                                                   resolveurl.resolver.ResolverError: File cannot be located or removed
```

**Comment by Gujal00** [comment]
They have implemented cloudflare turnstile challenge. Cannot be bypassed. Plugin is broken for now
