### ISSUE TITLE
VIMEO plugin --> urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION]

### ISSUE THREAD

**Issue by repobal** [Gujal00/ResolveURL#968]
Hello again.
We are developers of the Balandro addon and all logs are from Spain.

VIMEO exists and plays correctly; in All valid LINKS it ALWAYS gives this Result:

```python
2024-12-18 06:49:27.930 T:3208    error <general>: ResolveURL: URLError Error - From: Vimeo Link: https://player.vimeo.com/video/531187688/outro?on_site=0&type=videos&email=1|Referer=https://player.vimeo.com/video/531187688: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1136)>
2024-12-18 06:49:28.219 T:3208    error <general>: ######## ERROR #########
2024-12-18 06:49:28.219 T:3208    error <general>:     [Balandro.servers.vimeo.get_video_url] Traceback (most recent call last):
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\net.py", line 360, in _fetch
                                                       response = urllib_request.urlopen(req, timeout=timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 222, in urlopen
                                                       return opener.open(url, data, timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 649, in http_error_default
                                                       raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 403: Forbidden
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\net.py", line 369, in _fetch
                                                       response = opener.open(req, timeout=timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 531, in open
                                                       response = meth(req, response)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 640, in http_response
                                                       response = self.parent.error(
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 569, in error
                                                       return self._call_chain(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 649, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
                                                   urllib.error.HTTPError: HTTP Error 403: Forbidden
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 1354, in do_open
                                                       h.request(req.get_method(), req.selector, req.data, headers,
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 1256, in request
                                                       self._send_request(method, url, body, headers, encode_chunked)
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 1302, in _send_request
                                                       self.endheaders(body, encode_chunked=encode_chunked)
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 1251, in endheaders
                                                       self._send_output(message_body, encode_chunked=encode_chunked)
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 1011, in _send_output
                                                       self.send(msg)
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 951, in send
                                                       self.connect()
                                                     File "C:\Program Files\Kodi\system\python\Lib\http\client.py", line 1425, in connect
                                                       self.sock = self._context.wrap_socket(self.sock,
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 500, in wrap_socket
                                                       return self.sslsocket_class._create(
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1040, in _create
                                                       self.do_handshake()
                                                     File "C:\Program Files\Kodi\system\python\Lib\ssl.py", line 1309, in do_handshake
                                                       self._sslobj.do_handshake()
                                                   ssl.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1136)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\plugin.video.balandro\servers\vimeo.py", line 72, in get_video_url
                                                       resuelto = resolveurl.resolve(page_url)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 133, in resolve
                                                       return source.resolve()
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 205, in resolve
                                                       stream_url = resolver.get_media_url(self._host, self._media_id)
File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\plugins\vimeo.py", line 47, in get_media_url
                                                       html = self.net.http_GET(web_url, headers).content
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\net.py", line 245, in http_GET
                                                       return self._fetch(url, headers=headers, compression=compression, redirect=redirect, timeout=timeout)
                                                     File "C:\Users\migue\AppData\Roaming\Kodi\addons\script.module.resolveurl\lib\resolveurl\lib\net.py", line 377, in _fetch
                                                       response = opener.open(req, timeout=timeout)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 525, in open
                                                       response = self._open(req, data)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 542, in _open
                                                       result = self._call_chain(self.handle_open, protocol, protocol +
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 502, in _call_chain
                                                       result = func(*args)
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 1397, in https_open
                                                       return self.do_open(http.client.HTTPSConnection, req,
                                                     File "C:\Program Files\Kodi\system\python\Lib\urllib\request.py", line 1357, in do_open
                                                       raise URLError(err)
                                                   urllib.error.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1136)>
```

**Comment by Gujal00** [comment]
They have implemented cloudflare turnstile challenge. Cannot be bypassed. Plugin is broken for now
